## name: Rosé Pine
## author: mvllow
## license: MIT
## upstream: https://github.com/rose-pine/kitty/blob/main/dist/rose-pine.conf
## blurb: All natural pine, faux fur and a bit of soho vibes for the classy minimalist

foreground               #e9e8ff
## background            #191724
## for hyprland
background               #000000
selection_foreground     #e9e8ff
selection_background     #504d62

cursor                   #e9e8ff
cursor_text_color        #524f67
url_color                #c4a7e7

active_tab_foreground    #e9e8ff
active_tab_background    #26233a
inactive_tab_foreground  #6e6a86
inactive_tab_background  #191724

# black
color0   #151321
color8   #6e6a86

# red love
color1   #eb6f92
color9   #eb6f92

# green
color2   #73C48F
color10  #337336

# yellow gold rose
color3   #f6c177
color11  #ebbcba

# blue foam
color4   #9ccfd8
color12  #9ccfd8

# magenta iris
color5   #c4a7e7
color13  #c4a7e7

# cyan pine
color6   #31748f
color14  #193d4b

# white
color7   #e0def4
color15  #e0def4


