# Rosé Pine
include current-theme.conf

font_size 14
font_family FiraCode Nerd Font Mono
font_features FiraCodeNFM-Reg +ss01 +ss03 +ss04 +ss05 +cv02 +cv30 +cv31

bold_font        auto
italic_font      auto
bold_italic_font auto

cursor_shape block
cursor_blink_interval 0
cursor_shape_unfocused hollow
cursor_trail 1
cursor_trail_decay 0.2 0.3
cursor_trail_start_threshold 6

scrollbar scrolled-and-hovered
scrollbar_jump_on_click yes

touch_scroll_multiplier 5
mouse_hide_wait 0

copy_on_select clipboard
clear_selection_on_clipboard_loss yes
paste_actions replace-dangerous-control-codes,confirm-if-large
strip_trailing_spaces smart

repaint_delay 17
input_delay 1
sync_to_monitor no

confirm_os_window_close 0

editor nvim

enable_audio_bell no
linux_display_server wayland

draw_bold_text_with_bright_colors yes
term xterm-kitty

# for no background_image
# background_opacity 0.25
# background_blur 1

background_image /usr/share/wallpapers/Next/contents/images_dark/5120x2880-blured.png
background_image_layout scaled
background_tint 0.95

pixel_scroll yes
