## name: Rosé Pine
## author: mvllow
## license: MIT
## upstream: https://github.com/rose-pine/kitty/blob/main/dist/rose-pine.conf
## blurb: All natural pine, faux fur and a bit of soho vibes for the classy minimalist

# black
color0   #151321
color8   #6e6a86

# red love
color1   #eb6f92
color9   #f299ae

# green
color2   #13bb6d
color10  #5ee2a5

# yellow gold rose
color3   #f6c177
color11  #ebbcba

# blue foam
color4   #50CBE1
color12  #9ccfd8

# magenta iris
color5   #c4a7e7
color13  #d6c6e9

# cyan pine
color6   #31748f
color14  #3E9FAA

# white
color7   #c4c2d5
color15  #dbdaef


foreground               #e9e8ff
background               #000000
selection_foreground     #6e6a86
selection_background     #504d62

cursor                   #e9e8ff
cursor_text_color        background
url_color                #c4a7e7

active_tab_foreground    #e9e8ff
active_tab_background    #26233a
inactive_tab_foreground  #6e6a86
inactive_tab_background  #191724
