# allow reload of this file with PRE r
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded."

# switch prefix to control-a, unmap b, allow double-a to go through
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# -r repeat time (Default 500 millis)
set -g repeat-time 2000

# hide status line
set -g status off

# splits into cwd
bind '"' split-window -v -c "#{pane_current_path}"
bind %   split-window -h -c "#{pane_current_path}"

# colors
set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"
# set -g pane-border-style "fg=#6e6a86"                  # rose pine
# set -g pane-active-border-style "fg=#f6c177"           # rose pine
# set -g message-style "fg=#f6c177"                      # rose pine
set -g pane-border-style "fg=#3b4261"                  # tokyo night border
set -g pane-active-border-style "fg=#7aa2f7"           # tokyo night blue
set -g message-style "fg=#c0caf5"                      # tokyo night foreground

# mouse mode (scrolling, etc)
setw -g mouse on

# remove delay
set -sg escape-time 1

# vim style panes navigation
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# vim style through resizing
bind -r H resize-pane -L 6
bind -r J resize-pane -D 3
bind -r K resize-pane -U 3
bind -r L resize-pane -R 6

# vi-like copy mode while preserving escape as an exit key in copy mode
set -gw mode-keys vi
set -g status-keys emacs

# start selection with v
unbind -T copy-mode-vi Space
bind -T copy-mode-vi v send -X begin-selection

# Esc: first clear selection, then leave copy mode
bind -T copy-mode-vi Escape if-shell -F '#{selection_present}' 'send -X clear-selection' 'send -X cancel'

# Session control
unbind -T prefix C-s
bind f choose-session # legacy
bind C-c new-session

# Sessionizer/quick jump (very useful)
bind s display-popup -E "tmux list-sessions -F '#S' | fzf --reverse | xargs -r tmux switch-client -t"

# Keep windows alive after process exits (useful for quick restarts)
set -g remain-on-exit on

# Better history limit
set -g history-limit 100000

# List of plugins
set -g @plugin "tmux-plugins/tpm"
set -g @plugin "tmux-plugins/tmux-resurrect"
set -g @plugin "tmux-plugins/tmux-continuum"

# Auto-save every 5 minutes and do NOT restore on server start
set -g @continuum-save-interval "5"
set -g @continuum-restore "off"

# What to save (configure resurrect)
set -g @resurrect-strategy-nvim "session"
set -g @resurrect-strategy-vim "session"
set -g @resurrect-capture-pane-contents "on"
set -g @resurrect-processes '~happ->sudo -k happ'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run "~/.config/tmux/plugins/tpm/tpm"
